### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by ay8s** [philscott-dev/homebridge-stagg-ekg-plus#2]
Usually when I access HomeKit I see the kettle and get a grayed out UI. It will either then load up or show "not responding". 

Trying again sometimes fixes up the issue which confirms the server is working. I wondered if you've seen the same @philscott-dev or if you have any thoughts on what might be causing it?

Thanks for putting this together!

![image](https://user-images.githubusercontent.com/1058408/100973057-b9dc1080-34ee-11eb-896f-2297f14656a3.png)

![image](https://user-images.githubusercontent.com/1058408/100973071-bd6f9780-34ee-11eb-9f58-d08bb3448695.png)

![image](https://user-images.githubusercontent.com/1058408/100973081-bfd1f180-34ee-11eb-9e48-ea27d1034478.png)

**Comment by philscott-dev** [comment]
I haven't had any issues, myself. What version of Homebridge are you running? I'm on 1.2.3 + Homebridge UI on a Pi4, with no issues. But, I saw the Homebridge crew has rolled their latest stable release back to 1.1.6 on npm, due to connectivity issues with some plugins. I wonder if that might have something to do with it??? 

When I was initially developing the server project I _did_ have some weird issues with my Pi Zero W staying connected to wifi. I ended up having to go into my access points settings and bumping the transmission power up. You might want to take a look at that. If you can't adjust those settings, an interesting test would be to just put your Pi and kettle near your wifi access point and see if it behaves differently.

Hit me with some specifics about your setup though. Or, if you've got any homebridge logs, drop'm here and I'll try and take a look this weekend.

**Comment by ay8s** [comment]
Right now I'm using Hoobs which looks like it's using 1.1.6. 

I'll have a play with the positioning of the Pi and see about bumping the transmission power up. If I don't get anywhere with it I'll try and grab some more details and post them here. 👍
